# Generated by Django 5.2.4 on 2025-11-30 16:26

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('duration_months', models.PositiveIntegerField(default=1)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('fitness_goals', models.TextField(blank=True)),
                ('medical_conditions', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='admissions/photos/%Y/%m/%d/')),
                ('upi_id', models.CharField(blank=True, max_length=100)),
                ('agreed_terms', models.BooleanField(default=False)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('', 'Prefer not to say')], max_length=10, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price_month', models.DecimalField(decimal_places=2, default=Decimal('999.00'), max_digits=10)),
                ('price_annual', models.DecimalField(decimal_places=2, default=Decimal('9590.00'), max_digits=10)),
                ('duration_days', models.PositiveIntegerField(default=30)),
                ('perks', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True)),
                ('is_popular', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-is_popular', 'price_month', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('specialization', models.CharField(help_text='e.g., Strength & Conditioning • Powerlifting', max_length=200)),
                ('bio_short', models.TextField(default='', help_text='Short preview bio (1 sentence)', max_length=200)),
                ('bio_full', models.TextField(default='', help_text="Full detailed bio (shows when 'Read more' is clicked)")),
                ('image_url', models.URLField(help_text='Full URL to trainer image (Pinterest, CDN, etc.)', max_length=500)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first (0, 1, 2, 3, 4, 5)')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this trainer from the website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trainer',
                'verbose_name_plural': 'Trainers',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('upi_id', models.CharField(blank=True, max_length=100)),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('payment_mode', models.CharField(choices=[('UPI', 'UPI'), ('Card', 'Card'), ('Other', 'Other')], default='UPI', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='body.admission')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='admission',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='body.membershipplan'),
        ),
    ]
