# Generated by Django 5.2.4 on 2026-04-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0003_productorder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainer',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Supplements', 'Supplements'), ('Gear', 'Gear'), ('Apparel', 'Apparel')], default='Gear', max_length=20),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='upi_ref',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
