services:
  - type: web
    name: gym-shim
    runtime: python
    buildCommand: ./build.sh
    startCommand: gunicorn gym.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
